<h2>Search</h2>
<form id="Search" enctype="application/x-www-form-urlencoded" method="post" class="box" action="/">

    <input type="text" name="keyword" id="keyword" value="" />
    <input type="submit" name="search" id="search" value="search" />
</form>

<div class="box">
    <table id="results">
        <thead>
            <tr>
                <td>Project <span class="result_statistics">( 250 results )</span></td>
                <td>Owner</td>
                <td>Activity</td>
                <td>Watchers</td>
                <td>Forks</td>
                <td>Issues</td>
                <td>Wiki</td>
                <td>Pull Requets</td>
            </tr>
        </thead>
        <tbody>
            <?php
            for ($i=1;$i<4;$i++) {
                echo '
            <tr>
                <td>
                    <h3><a href="http://www.github.com">Zend-Framework--Doctrine-ORM--PHPUnit--Ant--Jenkins-CI--TDD-</a></h3>
                    <p>Best practice Zend Framework skeleton with Doctrine2 integration : 100% code coverage & build scripts using TDD</p>
                </td>
                <td>Eddie Jaoude</td>
                <td>3 days ago</td>
                <td>6</td>
                <td>5</td>
                <td>4</td>
                <td>3</td>
                <td>2</td>
            </tr>';
            }
                ?>
        </tbody>
    </table>
</div>