<h2>Search</h2>
<form id="Search" enctype="application/x-www-form-urlencoded" method="post" class="box" action="/">

    <input type="text" name="keyword" id="keyword" value="" />
    <input type="submit" name="search" id="search" value="search" />
</form>

<div class="box">
    <table id="results">
        <thead>
            <tr>
                <td>Project <span class="result_statistics">( <?php echo count($this->repos); ?> )</span></td>
                <td>Owner</td>
                <td>Language</td>
                <td>Activity</td>
                <td>Created</td>
                <td>Watchers</td>
                <td>Forks</td>
                <td>Issues</td>
                <td>Score</td>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->repos as $k => $v) {
                echo '
            <tr>
                <td>
                    <h3><a href="' . $v['url'] . '">' . $v['name'] . '</a></h3>
                    ' . (!empty($v['description']) ? '<p>' . $v['description'] . '</p>' : null) . '
                </td>
                <td><a href="https://github.com/' . $v['owner'] . '">' . $v['owner'] . '</a></td><!-- owner -->
                <td>' . $v['language'] . '</td><!-- langauge -->
                <td>' . $v['created'] . '</td><!-- created-->
                <td>' . $v['pushed'] . '</td><!-- activity -->
                <td>' . $v['watchers'] . '</td><!-- watchers -->
                <td>' . $v['forks'] . '</td><!-- Forks -->
                <td>' . $v['open_issues'] . '</td><!-- issues -->
                <td>' . $v['score'] . '</td><!-- score -->
            </tr>';
            }
                ?>
        </tbody>
    </table>
</div>
<?php var_dump($this->repos); ?>