<h2>Search</h2>
<form id="Search" enctype="application/x-www-form-urlencoded" method="post" class="box" action="/">

    <input type="text" name="keyword" id="keyword" value="" />
    <input type="submit" name="search" id="search" value="search" />
</form>

<ul id="results" class="box">
    <li>
        <div class="overview">
            <div class="fleft">
                <h3><a href="http://www.github.com">Zend-Framework--Doctrine-ORM--PHPUnit--Ant--Jenkins-CI--TDD-</a></h3>

                <p>Best practice Zend Framework skeleton with Doctrine2 integration : 100% code coverage & build scripts using TDD</p>
            </div>
            <div class="fright">
                <h4>Eddie Jaoude</h4>
                <table>
                    <tr>
                        <td class="project_stats">Forks</td>

                        <td>21</td>
                    </tr>
                    <tr>
                        <td>Watchers</td>
                        <td>14</td>
                    </tr>
                    <tr>

                        <td>Activity</td>
                        <td>3 days ago</td>
                    </tr>
                </table>
            </div>
            <div class="both"></div>
        </div>
        <div class="details">


        </div>
    </li>

</ul>
